language: node_js
sudo: required
services:
  - docker
cache:
  directories:
    - node_modules
node_js:
  - "8"
before_script:
  - npm install
  - docker-compose up -d
  - sleep 4
script:
  - npm test
after_script:
  - docker-compose kill